import './globals.css'
import { MainContainer } from './ui/MainContainer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <MainContainer>
        { children }
      </MainContainer>
    </html>
  )
}
